ethereum/py-ssz

ssz/__init__.py, ssz/codec.py, ssz/exceptions.py, ssz/sedes/__init__.py, ssz/sedes/boolean.py, ssz/utils.py, tests/core/test_boolean_serializer.py
SSZ needs to implemented by starting with the infrastructure. This module needs to follows this[ Spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/simple-serialize.md)
Issue #1
The infrastructure was mostly mimiced from `rlp`. The tests for `boolean serialization` and `deserialization` have been included.
=> Add basic API infrastructure with Boolean Support

setup.py
Use the same pytest version setting as py-evm
`"pytest>=3.6,<3.7"`
🐑
=> Bump pytest version >=3.6,<3.7

setup.py, ssz/sedes/bytes_n.py, tests/core/tree_hash/test_lists.py, tests/core/tree_hash/test_single_values.py
Issue #18
- add randomized tests to 
- single value sedes and lists sedes
- for uint, bytes, and bytes_n types.
- fix an error message
=> Fix 18, Add more Tree hash tests to uint, bytes, and bytes_n

ssz/sedes/base.py, ssz/sedes/integer.py, ssz/tree_hash/merkle_hash.py, tests/core/sedes/test_byte_serializer.py, tests/core/sedes/test_integer_serializer.py, tests/core/sedes/test_list_serializer.py, tests/core/test_serializable.py, tests/core/tree_hash/test_merkle_hash.py, tests/core/tree_hash/test_single_values.py
big endian -> little endian
Closes #27 
(updating the tests was no fun)
=> Little endian

ssz/codec.py, ssz/sedes/serializable.py, tests/sedes/test_speed.py
#36 part 1: Add cache for `encode`.
Basically copied the same logic from [pyrlp](https://github.com/ethereum/pyrlp/blob/7904316f3da420d8dda214dfe8fa168a8e866cfb/rlp/codec.py#L48-L70).
=> Add `encode` cache

.circleci/config.yml, ssz/sedes/__init__.py, ssz/sedes/container.py, tests/yaml_tests/test_yaml.py, tests/yaml_tests/yaml_test_execution.py
- Revive and fix the YAML test runner
- ~Enable running tree hash test vectors.~
- (unrelated, but not worthy of its own PR) make field names/sedes easier to access when given a container instance (implemented to simplify the test generator slightly)
=> Test Runner Updates

setup.py
Master branch is failing on CI due to an update of `pytest-xdist`.
- Use newest version of pytest and pytest-xdist
- Pin their versions so that this doesn't happen again
=> Update and pin pytest and pytest-xdist version

ssz/sedes/serializable.py
Missing `return` value in `SerializableBase.get_static_size()`
We need this patch for `BeaconState`.
Add it.
🐼
=> Fix SerializableBase.get_static_size()

setup.py, ssz/sedes/serializable.py, tests/misc/test_serializable.py, tests/misc/test_signed_serializable.py
Fix #62 `BaseSerializable.__eq__` bug
1. Move `pytest-watch` to test dep (so I can test with trinity)
2. Check `isinstance(other, BaseSerializable)` instead of `isinstance(other, Serializable)`
3. Add a test for equality
=> Fix `BaseSerializable.__eq__` bug

ssz/sedes/serializable.py, ssz/sedes/vector.py, tests/misc/test_signed_serializable.py
Fix #67 
1. Add `root_cache` and remove `hash_cache`.
2. Use `self.root == other.root` in `__eq__`.
=> hash_tree_root cache

ssz/sedes/serializable.py
Was removed in #68, but now I think it's still good to cache it.
Use `_hash_cache`.
Summary of approach.
🦎
=> Add `__hash__` cache back

ssz/sedes/serializable.py
Namely, one is a subclass of the other
Following up on @jannikluhn's idea to make class equality more flexible
=> Allows a more flexible relationship when comparing classes for `__eq__`

ssz/__init__.py, tests/tools/test_parsing_and_dumping.py
Reverts ethereum/py-ssz#69 to unblock new release.
Confirmed from @hwwhww that this revert will not affect Trinity implementation.
=> Revert "[Minor] import ssz; ssz.tools.do_something"

ssz/sedes/list.py
partition manually, to have bytes instead of tuples as BytesIO input
`partition` returns a series of tuples. Tuples are not accepted by BytesIO
Manually slice the input. Credits to @pipermerriam for confirming the problem and suggesting a fix.
=> fix list deserialization

scripts/benchmark/tree_hash.py, ssz/__init__.py, ssz/sedes/base.py, ssz/sedes/bitlist.py, ssz/sedes/bitvector.py, ssz/sedes/byte_list.py, ssz/sedes/byte_vector.py, ssz/sedes/container.py, ssz/sedes/list.py, ssz/sedes/serializable.py, ssz/sedes/signed_serializable.py, ssz/sedes/vector.py, ssz/tree_hash.py, tests/misc/test_serializable.py, tests/misc/test_signed_serializable.py, tests/tree_hash/test_aliases_tree_hash.py, tests/tree_hash/test_basic_sedes_trie_hash.py, tests/tree_hash/test_composite_tree_hash.py, tests/yaml_tests/yaml_test_execution.py
Fix #79 
- Rename `root` property to `hash_tree_root` for conflict No.1.
- And then found out we need to rename `hash_tree_root` function to `get_hash_tree_root` for conflict No.2.
🐘
=> Rename `hash_tree_root` function to `get_hash_tree_root` and `root` property to `hash_tree_root`

ssz/sedes/bitlist.py, ssz/sedes/bitvector.py, ssz/sedes/list.py, ssz/utils.py, tests/misc/test_utils.py
Sync with spec ethereum/eth2.0-specs#1292
1. Update `def merkleize(chunks: Sequence[Hash32], limit: int=None) -> Hash32`
2. Fix Bits `hash_tree_root` - will need to set `limit` parameter
3. Rename `pad_for` to `limit`
=> Sync v0.8.1

scripts/benchmark/tree_hash.py, ssz/constants.py, ssz/sedes/serializable.py, ssz/utils.py
Previously on https://github.com/ethereum/trinity/pull/848: `deepcopy` operation is the bottleneck.
1. Rework `copy`:
- Only need to deep copy if the field is mutable. 
2. Customize `deepcopy`:
- deepcopy the `self.__dict__.items()` and generate a new object.
`247.03 seconds` -> `101.59 seconds` improvement for `test_demo.py`.
Note: If this approach is accepted, `pyrlp` could be improved too. It's about 3.5x better for `block.copy()` operation.
=> [Turbo] Rework `BaseSerializable.copy` and `BaseSerializable.__deepcopy__`

ssz/sedes/basic.py, ssz/sedes/bitlist.py, ssz/sedes/bitvector.py, ssz/sedes/byte_vector.py, ssz/sedes/list.py, ssz/sedes/vector.py, ssz/utils.py
`merkleize(chunks, limit, cache)` was supporting both `cache is None` and `cache is not None` cases, that made it too messy.
Rafactor and separate it into `merkleize_with_cache(chunks: Sequence[Hash32], cache: CacheObj, limit: int=None) -> Tuple[Hash32, CacheObj]` and `merkleize(chunks: Sequence[Hash32], limit: int=None) -> Hash32` functions.
Summary of approach.
=> Refactor `merkleize`

ssz/cache/utils.py, ssz/sedes/vector.py
For `List`, the `sedes_name` is only `List`. Need more specific identifier.
Add `max_length` to the `key`.
=> Hotfix for #87

ssz/cache/utils.py, ssz/sedes/base.py, ssz/sedes/basic.py, ssz/sedes/bitlist.py, ssz/sedes/bitvector.py, ssz/sedes/boolean.py, ssz/sedes/byte.py, ssz/sedes/byte_vector.py, ssz/sedes/container.py, ssz/sedes/list.py, ssz/sedes/serializable.py, ssz/sedes/uint.py, ssz/sedes/vector.py, tests/misc/test_serializable.py, tests/sedes/test_basic_sedes.py, tests/sedes/test_bitlist_serializer.py, tests/sedes/test_bitvector_serializer.py, tests/sedes/test_composite_sedes.py, tests/sedes/test_sedes_aliases.py
Replace #90
Thanks to @ralexstokes for finding this bug!
1. Apply partial #88 refactoring: split `CompositeSedes` into two subclasses `HomogeneousCompositeSedes` (including `List` and `Vector`) and `Container` (nonhomogeneous).
2. Add `get_sedes_id` API to identify the sedes for cache key.
- `Boolean` or `Byte`
- just return the class name `Boolean` or `Byte`.
- `UInt`
- return `f'UInt{bit_length}'`.
- `ByteVector`, `Bitlist`, `Bitvector`
- return `'f{sedes.__class__.name}{length}'`.
- `HomogeneousCompositeSedes`
- use `element_sedes.get_sedes_id()` and `max_length` and as the ID. e.g., `List(uint8, 2)` -> `'List(UInt8,2)'`
- `Container`
- use `','.join(field.get_sedes_id() for field in self.field_sedes)` as the ID. e.g., `Container((uint8, bytes32))` -> `'UInt8,ByteVector32'`.
- …
=> Add more meta info in cache key

ssz/sedes/serializable.py
It was removed when I used simple `dict` as the `cache`. Now it should be safe with `LRU` cache.
When `b = a.copy()`, set the `b.cache` to `a.cache`.
=> Fix copy cache

scripts/benchmark/hash_tree.py, setup.py, ssz/hash_tree.py, ssz/utils.py, tests/tree_hash/test_hash_tree.py, tox.ini
This PR implements a class representing tree hashes. It is immutable and provides the same interface as a pyrsistent pvector, with entries corresponding to chunks. The full tree is stored and on updates only the affected hashes are recomputed.
Example usage:
```Py
hash_tree_1 = HashTree.compute([CHUNK1, CHUNK2], limit=4)  # create a new hash tree
hash_tree_2 = hash_tree_1.set(0, CHUNK3)  # update chunk 0
hash_tree_3 = hash_tree_2.append(CHUNK4)  # append a chunk at the end
print(hash_tree_3[1])  # access chunk 1
print(hash_tree_3.root)  # access root
hash_tree_4 = hash_tree_3.delete(2)  # delete chunk 2 (this recomputes the full tree at the moment)
evolver = hash_tree_4.evolver()  # mutable copy
evolver[1] = CHUNK1
evolver[2].append(CHUNK23)
hash_tree_5 = evolver.persist()  # persist …
```
=> Tree Hash Object

ssz/hashable_container.py
`hashablify_value` used to convert everything to iterables which requires recomputation of the hash tree.
Just return the original value if it already is hashable.
=> Add passthrough for hashables in hashablify_value

ssz/sedes/serializable.py
A deprecated import is causing a warning downstream in Trinity.
```
/home/cburgdorf/Documents/hacking/ef/trinity/venv/lib/python3.7/site-packages/ssz/sedes/serializable.py:70: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
class BaseSerializable(collections.Sequence):
```
Import `Sequence` from `collections.abc` rather than `collections`
=> Fix deprecation warning

setup.py
The pin resulted in dependency conflicts with other libraries required by Trinity.
Remove the pin
=> Remove pyrsistent pin

ssz/sedes/bitvector.py, tests/sedes/test_bitvector_instantiation.py, tests/sedes/test_bitvector_serializer.py
According to the spec, an empty bitvector is illegal and so an error should be raised if bit_count <=0
Issue #111
The bound on bit_count was adjusted so that an error is raised if it is zero or negative
=> Prevent bitvectors of length 0

ssz/sedes/bitlist.py, tests/sedes/test_bitlist_serializer.py
A sequence of bytes ending with 0x00 cannot be a serialisation of a bitlist.
As a consequence it should not be possible to deserialise such sequence into a bitlist.
The current implementation allows that.
Issue #109 
This issue was uncovered as part of the formal verification of the Eth2.0 specs using Dafny: [issue 4](https://github.com/PegaSysEng/eth2.0-dafny/issues/4)
Deserialise into bitlist code; add a test to check that the last byte is not null. If it is raise an exception.
Tests: two tests provided with illegal input for deserialising into biltists and check that the exception is actually raised.
=> Deserialise seq of bytes into bitlist only if last byte is non null

.circleci/config.yml, docs/releases.rst, setup.py, ssz/__init__.py, ssz/hashable_structure.py, ssz/sedes/__init__.py, ssz/sedes/byte_list.py, tests/sedes/test_sedes_aliases.py, tests/tree_hash/test_aliases_tree_hash.py
Fix #118 
Add a `ByteList` class that more efficiently encodes a variable-length series of bytes. It's also more convenient than sending in an iterable of single bytes. (since if you just send a `bytes` in python, it will yield each element as an `int` instead, which fails on a `List(Byte)`.
Generally, follow the same pattern as `ByteVector`. Add tests to make sure that `Byte(List)` is equivalent to `ByteList()`.
Skipped `.get_hash_tree_root_and_leaves()` implementation for now, for lack of context.
TODO
=> Encode a byte list more naturally

Makefile, docs/release_notes.rst, newsfragments/109.bugfix.rst, newsfragments/111.bugfix.rst, newsfragments/116.bugfix.rst, newsfragments/118.feature.rst, newsfragments/120.internal.rst, newsfragments/121.internal.rst, newsfragments/124.doc.rst, newsfragments/124.misc.rst, tests/sedes/test_composite_sedes.py
There weren't any release notes added for the last few PRs
- Added them as best as I could understand
- Reversed the sorting order of the release notes, so most recent is up top
- Added some bonus tests that I noticed would improve the new `ByteList` (and older `ByteVector`) sedes
- Don't auto-generate docs for tests
[//]: # (Stay ahead of things, add list items here!)
[//]: # (For important changes that should go into the release notes please add a newsfragment file as explained here: https://github.com/ethereum/py-ssz/blob/master/newsfragments/README.md)
[//]: # (See: https://ssz.readthedocs.io/en/latest/contributing.html#pull-requests)
=> Add release notes

docs/release_notes.rst, docs/ssz.cache.rst, docs/ssz.rst, docs/ssz.sedes.rst, docs/ssz.tools.rst, newsfragments/109.bugfix.rst, newsfragments/111.bugfix.rst, newsfragments/116.bugfix.rst, newsfragments/118.feature.rst, newsfragments/120.internal.rst, newsfragments/121.internal.rst, newsfragments/124.doc.rst, newsfragments/124.misc.rst, newsfragments/125.breaking.rst, ssz/sedes/byte_list.py
Ran `make notes bump=minor` (minor, because of a breaking change in a v0 library).
Also:
- Manually expanded the miscellaneous changes into internal
- Fixed a docstring in ByteList so that `bytes` is linked correctly
- Pushed Breaking Changes to the top, it should be the most important thing to notice as a skimming reader.
=> Compile release notes for v0.3.0

newsfragments/132.internal.rst, setup.py
`eth-utils` requirement version was pinned <2
Closes #127 
Bumped to >=2
=> bump eth-utils requirement to >=2

.readthedocs.yml, newsfragments/133.internal.rst
ReadTheDocs will soon require `build.os` config
Added to readthedocs.yml
=> add build.os to rtd config

newsfragments/140.internal.rst, setup.py, tests/core/misc/test_pyrsistent.py
`pyrsistent` dep is has an upper pin that only officially supports up to py38
Related to Issue #140
Closes #140
Remove upper pin on `pyrsistent` dep.
The upper pin exists because we make use of an internal `transform` function, but it hasn't changed for years and the maintainer doesn't expect it to - https://github.com/tobgu/pyrsistent/issues/180
We already have a test for our usage of `transform` in `test_hashable_structures`, so I've added a test to make sure the source code hasn't changed.
=> remove pyrsistent upper pin

.pre-commit-config.yaml, Makefile, ssz/abc.py, ssz/codec.py, ssz/hash_tree.py, ssz/hashable_structure.py, ssz/sedes/__init__.py
=> Add some more types
